package Ventanas;

import javax.swing.table.DefaultTableModel;
import Validaciones.Numeros;
import javax.swing.JOptionPane;
import Procesos.*;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class Conciertos_Adm extends javax.swing.JFrame {

    DefaultTableModel modeloTabla, modeloPrecios;
    Object filas[][] = {};
    String cabecera[] = {"IDEvento", "ID_Cat", "Nombre", "Tipo", "Fecha", "Hora", "Duración", "Precio", "Tickets"};
    Object filas2[][] = {};
    String cabecera2[] = {"ID_Ev", "Evento", "Zona", "Cantidad", "Sub_Total"};

    public Conciertos_Adm() {
        initComponents();
        modeloTabla = new DefaultTableModel(filas, cabecera) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };
        jTable1.setModel(modeloTabla);
        //para ordenar la tabla
        TableRowSorter<TableModel> orden = new TableRowSorter<TableModel>(modeloTabla);
        jTable1.setRowSorter(orden);

        ProcTablas pt = new ProcTablas();

        pt.listaEvento("RO001", "CO", "PSV", "Rock", "13/07/2018", "18:30 pm", "120 min", 45, 500, modeloTabla);
        pt.listaEvento("RO002", "CO", "AC-DC", "Rock", "14/10/2018", "17:30 pm", "110 min", 105, 800, modeloTabla);
        pt.listaEvento("RO003", "CO", "6 voltios", "Rock", "01/04/2018", "15:00 pm", "110 min", 40, 500, modeloTabla);
        pt.listaEvento("SA001", "CO", "DLG", "Salsa", "13/03/2018", "18:30 pm", "120 min", 45, 600, modeloTabla);
        pt.listaEvento("SA002", "CO", "Víctor Manuel", "Salsa", "10/08/2018", "18:00 pm", "100 min", 55, 750, modeloTabla);
        pt.listaEvento("SA003", "CO", "Oscar de León", "Salsa", "17/09/2018", "17:40 pm", "110 min", 60, 850, modeloTabla);
        pt.listaEvento("CU001", "CO", "Grupo 5", "Cumbia", "27/10/2018", "17:20 pm", "110 min", 57, 850, modeloTabla);
        pt.listaEvento("CU002", "CO", "Agua Marina", "Cumbia", "13/11/2018", "16:00 pm", "130 min", 49, 800, modeloTabla);
        pt.listaEvento("CU003", "CO", "Coazón Serrano", "Cumbia", "20/04/2018", "18:00 pm", "100 min", 40, 950, modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbConciertos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtnomev = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtfec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txthora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtprec = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttic = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbConciertos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rock", "Salsa", "Cumbia" }));
        cmbConciertos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbConciertosItemStateChanged(evt);
            }
        });
        cmbConciertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConciertosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setText("Nombre de evento:");

        txtnomev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomevKeyTyped(evt);
            }
        });

        jLabel11.setText("Tipo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnomev, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtnomev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 230));

        btnAgregar.setText("Agregar Evento");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Evento");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btnAgregar)
                .addGap(105, 105, 105)
                .addComponent(btnEliminar)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 850, 90));

        jLabel1.setText("Nombre:");

        txtnom.setEnabled(false);

        jLabel2.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rock", "Salsa", "Cumbia" }));
        cmbTipo.setEnabled(false);
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha:");

        txtfec.setEnabled(false);

        jLabel4.setText("Hora:");

        txthora.setEnabled(false);

        jLabel5.setText("Duración:");

        txtdura.setEnabled(false);

        jLabel6.setText("Precio:");

        txtprec.setEnabled(false);

        jLabel7.setText("Tickets:");

        txttic.setEnabled(false);

        btnAceptar.setText("Agregar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdura, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtfec, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtprec, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txttic, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(btnAceptar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtfec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtdura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtprec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 850, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbConciertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConciertosActionPerformed

    }//GEN-LAST:event_cmbConciertosActionPerformed

    private void cmbConciertosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbConciertosItemStateChanged
        TableRowSorter cat = new TableRowSorter(jTable1.getModel());
        jTable1.setRowSorter(cat);
        switch (cmbConciertos.getSelectedIndex()) {
            case 0:
                cat.setRowFilter(RowFilter.regexFilter("Rock", 3));
                break;
            case 1:
                cat.setRowFilter(RowFilter.regexFilter("Salsa", 3));
                break;
        }
    }//GEN-LAST:event_cmbConciertosItemStateChanged

    private void txtnomevKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomevKeyTyped
        TableRowSorter nomev = new TableRowSorter(jTable1.getModel());
        jTable1.setRowSorter(nomev);
        String filtro = txtnomev.getText();
        nomev.setRowFilter(RowFilter.regexFilter(filtro, 2));
    }//GEN-LAST:event_txtnomevKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        txtnom.setEnabled(true);
        cmbTipo.setEnabled(true);
        txtfec.setEnabled(true);
        txthora.setEnabled(true);
        txtdura.setEnabled(true);
        txtprec.setEnabled(true);
        txttic.setEnabled(true);
        btnAceptar.setEnabled(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ProcTablas pt = new ProcTablas();
        int numal = (int) ((Math.random() * (10 - 50) + 50));
        String nombre = txtnom.getText();
        String tipo = cmbTipo.getSelectedItem().toString();
        String fecha = txtfec.getText();
        String hora = txthora.getText();
        String duracion = txtdura.getText();
        if (!txtnom.getText().isEmpty() && !txthora.getText().isEmpty() && !txtdura.getText().isEmpty()) {
            if (!Validaciones.Fechas.validarFecha(fecha)) {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar una fecha válida");
                txtfec.requestFocusInWindow();
                return;
            } else {
                if (!Numeros.precValido(txtprec.getText()) || Float.parseFloat(txtprec.getText()) <= 0) {
                    JOptionPane.showMessageDialog(rootPane, "Precio no válido");
                    txtprec.requestFocusInWindow();
                    return;
                } else {
                    if (!Numeros.esNumero(txttic.getText()) || Integer.parseInt(txttic.getText()) <= 0) {
                        JOptionPane.showMessageDialog(rootPane, "Cantidad no válida");
                        txttic.requestFocusInWindow();
                        return;
                    } else {
                        float precio = Float.parseFloat(txtprec.getText());
                        int cantidad = Integer.parseInt(txttic.getText());
                        switch (cmbTipo.getSelectedIndex()) {
                            case 0:
                                pt.listaEvento("RO0" + numal, "CO", nombre, tipo, fecha, hora, duracion, precio, cantidad, modeloTabla);
                                break;
                            case 1:
                                pt.listaEvento("SA0" + numal, "CO", nombre, tipo, fecha, hora, duracion, precio, cantidad, modeloTabla);
                                break;
                            case 2:
                                pt.listaEvento("CU0" + numal, "CO", nombre, tipo, fecha, hora, duracion, precio, cantidad, modeloTabla);
                                break;
                        }                        
                        txtnom.setText("");
                        txtfec.setText("");
                        txtdura.setText("");
                        txtprec.setText("");
                        txthora.setText("");
                        txttic.setText("");

                        cmbTipo.setEnabled(false);
                        txtfec.setEnabled(false);
                        txthora.setEnabled(false);
                        txtdura.setEnabled(false);
                        txtprec.setEnabled(false);
                        txttic.setEnabled(false);
                        btnAceptar.setEnabled(false);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No pueden haber campos vacíos");
            return;
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una fila para eliminar");
        } else {
            int op = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar la fila?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                modeloTabla.removeRow(fila);
            } else {
                return;
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conciertos_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conciertos_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conciertos_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conciertos_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conciertos_Adm().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbConciertos;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField txtdura;
    private javax.swing.JTextField txtfec;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnomev;
    private javax.swing.JTextField txtprec;
    private javax.swing.JTextField txttic;
    // End of variables declaration//GEN-END:variables

}
